### ISSUE TITLE
[Docs] Add CONTRIBUTING.md 

### ISSUE THREAD

**Issue by murilommen** [LeonardoSirino/FuzzyTableExtractor#1]
It would be nice to have a contribution guide, with:
- how to setup the environment and start working
- the code and documentation styleguide
- the branching and contribution pattern (gitflow, review process, etc.)

Great work so far! :)

**Comment by LeonardoSirino** [comment]
Added a basic contribution guide to the project root: [link](https://github.com/LeonardoSirino/FuzzyTableExtractor/blob/main/CONTRIBUTING.md)
